title: Stackbit Fresh Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Personal blogging theme for Stackbit
layout_style: overflow
palette: blue
header:
  title: Stackbit Fresh
  tagline: Header Tagline
  profile_img: images/avatar.png
  background: dark
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: Blog
      url: /blog/
      style: link
    - label: Style Guide
      url: /style-guide/
      style: link
    - label: About
      url: /about/
      style: link
    - label: Contact
      url: /contact/
      style: link
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon_class: fa-instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: fa-github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      style: icon
      icon_class: fa-dev
      new_window: true
footer:
  content: '&copy; All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      style: link
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
