plugins:
  - jekyll-remote-theme
  
remote_theme: chromatical/jekyll-materialdocs

logo: /path/to/logo.png # an absolute or relative image path to use as the site logo
mdl_colors: indigo-pink # a supported Material Design Lite color scheme
copyright: Your Name # will override the copyright notice (default is site title)
search: true # enabled by default, set to false to disable site search
menu_style: dropdown # will only show child menu items for the main item selected

menu: Example Page # will use this as the menu item text instead of title, set to false to remove from menu
tab: true # will open this page in a new tab
parent: index.md # will make this menu item a child of the index.md item
weight: 2 # smaller weights rise to the top of the menu
mdl_colors: deep_orange-blue # override global color scheme for this page
search: false # hides this page from search results
