remote_theme: stackbithq/stackbit-theme-fresh
title: Stackbit Fresh Theme
baseurl: /
permalink: "/:title/"
collections:
  posts:
    permalink: "/posts/:title/"
description: Personal blogging theme for Stackbit
layout_style: overflow
palette: blue
header:
  title: Stackbit Fresh
  tagline: Header Tagline
  profile_img: images/avatar.png
  background: dark
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
    - label: FAQs
      url: /blog/
      style: link
    - label: Career Paths
      url: /style-guide/
      style: link
    - label: Learning Resources
      url: /about/
      style: link
    - label: Contribution Guidelines
      url: /contact/
      style: link
  has_social: true
  social_links:
    - label: Facebook
      url: 'https://www.facebook.com/groups/softdevpk'
      style: icon
      icon_class: fa-facebook
      new_window: true
      new_window: true
footer:
  content: "&copy; All rights reserved."
  links:
    - label: Made with Stackbit.
      url: "https://www.stackbit.com"
      style: link
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
